# Generated by Django 5.2 on 2025-06-16 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Test veri setinin adı', max_length=100)),
                ('description', models.TextField(help_text='Test veri seti açıklaması')),
                ('file', models.FileField(help_text='Test veri seti dosyası (.csv)', upload_to='test_data/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Aktif test veri seti mi?')),
            ],
            options={
                'verbose_name': 'Test Data',
                'verbose_name_plural': 'Test Data',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('school_number', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('model_file', models.FileField(help_text='KNN model dosyası (.pkl)', upload_to='user_models/')),
                ('accuracy', models.FloatField(blank=True, help_text='Model doğruluk oranı', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('test_data', models.ForeignKey(help_text='Kullanılan test veri seti', null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.testdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Model',
                'verbose_name_plural': 'User Models',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
