# Generated by Django 5.2 on 2025-06-16 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_testdata_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
