# Generated by Django 5.2.4 on 2025-07-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_delete_student_delete_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="algorithm_type",
            field=models.CharField(
                choices=[
                    ("knn", "K-Nearest Neighbors (KNN)"),
                    ("naive_bayes", "Naive Bayes"),
                ],
                default="knn",
                help_text="Seçilen makine öğrenmesi algoritması",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="model_file",
            field=models.FileField(
                help_text="Model dosyası (.pkl)", upload_to="user_models/"
            ),
        ),
    ]
