# Generated by Django 5.2.4 on 2025-07-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_usermodel_algorithm_type_alter_usermodel_model_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="class_labels",
            field=models.JSONField(blank=True, help_text="Sınıf etiketleri", null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="classification_report",
            field=models.JSONField(
                blank=True, help_text="Classification report verisi", null=True
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="confusion_matrix",
            field=models.JSONField(
                blank=True, help_text="Confusion matrix verisi", null=True
            ),
        ),
    ]
